DROP TABLE ROLE;
DROP TABLE USERS;

CREATE TABLE "USERS" ("USER_ID" NUMBER, "USERNAME" NVARCHAR2(50), "PASSWORD" NVARCHAR2(100));
ALTER TABLE "USERS" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("USER_ID") ENABLE;
ALTER TABLE "USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
ALTER TABLE "USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  
CREATE TABLE "ROLE" ("USER_ID" NUMBER, "ROLE_NAME" NVARCHAR2(20));
ALTER TABLE "ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
ALTER TABLE "ROLE" ADD CONSTRAINT "ROLE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
commit;