
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (3,'Does Neighbours really represent Australia','The Australian soap opera Neighbours is now 30 years old � but where is the diversity? Ramsay Street doesn�t reflect modern Australia, writes Clementine Ford',to_date('11-11-07','DD-MM-RR'),'Australia culture',to_date('16-11-07','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (4,'New protocol http2 to speedup the web','New protocol http2 to speedup the web',to_date('16-02-15','DD-MM-RR'),'New protocol http2',to_date('16-02-15','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (5,'Why museums hide masterpieces away','n major museums around the world, some truly great works of art are hidden away from public view. What are they � and why can�t we see them? Kimberly Bradley finds out.',to_date('12-12-10','DD-MM-RR'),'Masterpieces from scotland',to_date('16-12-10','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (6,'Looking: A new way to break a TV taboo','The HBO series Looking is one of the most revolutionary depictions of gay life ever on TV � and that�s because it makes it totally ordinary, writes Keith Uhlich',to_date('23-06-09','DD-MM-RR'),'TV taboo to be broken',to_date('24-06-09','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (7,'Germany riot in Frankfurt targets new ECB headquarters','Anti-austerity demonstrators in the German city of Frankfurt have set police cars alight and tTESTHRown stones in protest at the opening of a new base for the European Central Bank',to_date('29-04-01','DD-MM-RR'),'Destabilized situation in Frankfurt',to_date('30-04-01','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (8,'Serbia arrests seven over 1995 Srebrenica massacre','Serbian police have arrested seven men accused of taking part in the slaughter of over 1,000 Muslims at a warehouse on the outskirts of Srebrenica',to_date('17-05-12','DD-MM-RR'),'Political decision in Serbia',to_date('24-06-12','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (9,'Syria claims shooting down of US drone over Latakia','The Syrian military says it has shot down a US drone near the city of Latakia, a stronghold of President Bashar al-Assad in north-west Syria.',to_date('07-10-11','DD-MM-RR'),'Clashes in Asia',to_date('11-10-11','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (10,'Solar Impulse: Plane sets out on two-hop journey to Myanmar','The solar-powered plane attempting to fly around the world is in the air again, crossing India and hoping to make it to Myanmar on Thursday',to_date('02-02-02','DD-MM-RR'),'Myanmar climate',to_date('03-03-02','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (11,'Switzerland to return Sani Abacha loot to Nigeria','Switzerland will return to Nigeria some $380m (?260m) allegedly looted by ex-military ruler Sani Abacha, an official has said.\n    The transfer, to be conducted under the supervision of the World Bank, will end a 16-year case against the Abacha family',to_date('14-08-13','DD-MM-RR'),'Sani Abacho return Nigeria police',to_date('16-08-13','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (12,'The online dating site sued for targeting married people','An online dating site that targets married people is being accused of breaking the law. A court in\n    France must now decide whether the company is illegally encouraging spouses to cheat',to_date('05-05-05','DD-MM-RR'),'Online daing',to_date('06-05-05','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (13,'Who is The Archangel of Death fighting IS','The fight against Islamic State in Iraq is raging in Tikrit, where government forces are being helped by\n    dozens of Shia militias. One soldier in particular has gained thousands of fans online - but his story is also a revealing insight into Iran''s propaganda machine',to_date('07-07-05','DD-MM-RR'),'BBC trending',to_date('08-07-05','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (14,'Will California Dry Up Fall Off','It got me wondering, just how bad and widespread is California''s drought? I did a few web searches and\n    found lots of dramatic before-and-after pictures of its lakes, which are down to about 35% of capacity statewide',to_date('17-07-05','DD-MM-RR'),'California earthquake',to_date('20-07-05','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (15,'Millions of people in the UK and northern Europe have glimpsed the best solar eclipse in years','In all parts of the UK the eclipse reached at least 83% and the darkness peaked at about 09:35 GMT.\n    Actual viewing opportunities were heavily dependent on the cloud cover that sTESTHRouded much of the country. The deep shadow formed first in the North Atlantic,\n     before sweeping up into the Arctic Circle and ending at the North Pole. The UK will not see a solar eclipse on this scale again until 2026',to_date('02-11-08','DD-MM-RR'),'Solar eclipse witnessed by millions',to_date('07-11-08','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (16,'The uniformed security guard waves us down to the newest city in the Kingdom of Saudi Arabia','Peppered with cranes, the city - or building site to be more accurate - lies one-and-a-half hours drive north of Jeddah between the Red Sea and scrubby desert',to_date('22-04-13','DD-MM-RR'),'Saudi Arabia''s new desert megacity',to_date('26-04-13','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (17,'EU leaders say Greece has agreed to come up with a new reform plan','The development came after marathon talks between Greek PM Alexis Tsipras, German Chancellor Angela Merkel and other European leaders in Brussels',to_date('12-12-12','DD-MM-RR'),'Greece to draft new reform plan within days - EU leaders',to_date('14-12-12','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (18,'Cheating in exams is fairly comMM in the Indian state of Bihar','Many students smuggled in textbooks and notes into the examination centres despite tight security - and parents and friends were photographed scaling the walls\n    of test centres to pass on answers to students during the current secondary school examinations',to_date('15-03-01','DD-MM-RR'),'India students caught cheating in exams in Bihar',to_date('16-03-01','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (19,'Singapore has begun seven days of national mourning of its founding father','Mr Lee, who was 91, led Singapore''s transformation from a small port city to one of the wealthiest nations in the world. World leaders have paid\n    tribute to Mr Lee, who served as the city-state''s prime minister for 31 years',to_date('05-09-08','DD-MM-RR'),'Singapore mourns founding father Lee Kuan Yew',to_date('05-10-08','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (20,'France centre-right UMP party taken first place in the first round of local elections','Projections suggest that the far-right National Front - despite strong gains - came second with about 25% of the vote, behind the conservatives on about 30%',to_date('20-01-15','DD-MM-RR'),'France local elections',to_date('22-01-15','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (1,'Netanyahu Likud storms to victory','Prime Minister Benjamin Netanyahu''s right-wing Likud Party has won a surprise victory in Israel''s election.',to_date('24-02-12','DD-MM-RR'),'Israel election',to_date('28-02-12','DD-MM-RR'));
Insert into NEWS (NEWS_ID,SHORT_TEXT,FULL_TEXT,CREATION_DATE,TITLE,MODIFICATION_DATE) values (2,'South Africa need to score 13 more runs','Chameera gets the hook after two rather forgettable overs, and fellow right-arm seamer Thisara Perera is on as Sri Lanka''s sixth bowler, looking to make amends for his third-ball duck.',to_date('07-07-09','DD-MM-RR'),'Cricket superbowl',to_date('08-07-09','DD-MM-RR'));

Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (3,'Jack',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (4,'Garry',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (5,'Tom',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (6,'William',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (7,'Ivan',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (8,'Slava',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (9,'Peter',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (10,'Alex',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (11,'Ulysses',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (12,'Abraam',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (13,'Robby',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (14,'Jacklin',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (15,'Marylin',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (16,'Anetta',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (17,'Margarete',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (18,'Paul',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (19,'Diego',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (20,'Urgen',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (1,'John',null);
Insert into AUTHOR (AUTHOR_ID,NAME,EXPIRED) values (2,'Boris',null);

Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (2,2);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (4,4);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (5,2);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (6,2);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (7,7);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (8,4);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (9,10);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (10,7);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (11,10);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (12,11);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (13,11);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (14,11);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (15,13);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (16,16);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (17,13);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (18,18);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (19,7);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (20,18);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (1,1);
Insert into NEWS_AUTHOR (NEWS_ID,AUTHOR_ID) values (3,1);

Insert into TAG (TAG_ID,TAG_NAME) values (3,'place');
Insert into TAG (TAG_ID,TAG_NAME) values (4,'sorry');
Insert into TAG (TAG_ID,TAG_NAME) values (5,'good');
Insert into TAG (TAG_ID,TAG_NAME) values (6,'heavy');
Insert into TAG (TAG_ID,TAG_NAME) values (7,'oracle');
Insert into TAG (TAG_ID,TAG_NAME) values (8,'bad');
Insert into TAG (TAG_ID,TAG_NAME) values (9,'sport');
Insert into TAG (TAG_ID,TAG_NAME) values (10,'pretty');
Insert into TAG (TAG_ID,TAG_NAME) values (11,'bored');
Insert into TAG (TAG_ID,TAG_NAME) values (12,'funny');
Insert into TAG (TAG_ID,TAG_NAME) values (13,'travel');
Insert into TAG (TAG_ID,TAG_NAME) values (14,'ride');
Insert into TAG (TAG_ID,TAG_NAME) values (15,'car');
Insert into TAG (TAG_ID,TAG_NAME) values (16,'exotic');
Insert into TAG (TAG_ID,TAG_NAME) values (17,'politic');
Insert into TAG (TAG_ID,TAG_NAME) values (18,'economic');
Insert into TAG (TAG_ID,TAG_NAME) values (19,'culture');
Insert into TAG (TAG_ID,TAG_NAME) values (20,'live');
Insert into TAG (TAG_ID,TAG_NAME) values (1,'cool');
Insert into TAG (TAG_ID,TAG_NAME) values (2,'wonderful');

Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (2,1);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (2,3);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (3,3);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (3,4);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (3,5);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (5,5);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (6,6);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (7,6);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (9,8);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (9,9);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (9,10);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (10,8);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (10,11);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (12,8);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (12,12);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (13,3);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (13,13);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (13,14);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (1,1);
Insert into NEWS_TAG (NEWS_ID,TAG_ID) values (1,2);

Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (3,'Manny Williams did it for second times!!! yeeee...',to_date('12-07-09','DD-MM-RR'),2);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (4,'this man will save Israeli!!!',to_date('02-03-12','DD-MM-RR'),1);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (5,'british museum - my favourite one',to_date('19-12-10','DD-MM-RR'),5);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (6,'but boston pitcher failed lats shot!??',to_date('15-07-09','DD-MM-RR'),2);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (7,'Why old protocol not satisfy them???',to_date('18-02-15','DD-MM-RR'),4);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (8,'scotland artefacts are awesome!!!',to_date('26-12-10','DD-MM-RR'),5);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (9,'Kimberley digs into truth greatly',to_date('22-12-10','DD-MM-RR'),5);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (10,'Most of them nevertheless will use http!',to_date('25-02-15','DD-MM-RR'),4);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (11,'Please dont post it any more',to_date('01-07-09','DD-MM-RR'),6);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (12,'conflict in serbia wont stop!!!',to_date('27-06-12','DD-MM-RR'),8);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (13,'plane that flyes over pacific ocean...',to_date('11-03-02','DD-MM-RR'),10);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (14,'what taboo they wanna break??',to_date('02-07-09','DD-MM-RR'),6);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (15,'how much it will be cost??',to_date('03-07-09','DD-MM-RR'),6);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (16,'in 1995 was a hard year of all serbians!',to_date('29-06-12','DD-MM-RR'),8);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (17,'it is incredible!',to_date('13-03-02','DD-MM-RR'),10);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (18,'i live in switzerland and i not accept this. so far',to_date('20-08-13','DD-MM-RR'),11);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (19,'officials hide real numbers!!!..',to_date('21-08-13','DD-MM-RR'),11);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (20,'really really positive emotions reading it',to_date('25-08-13','DD-MM-RR'),11);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (1,'arabic world do not trust...',to_date('01-03-12','DD-MM-RR'),1);
Insert into COMMENTS (COMMENT_ID,COMMENT_TEXT,CREATION_DATE,NEWS_ID) values (2,'better play volleyball than this game',to_date('09-07-09','DD-MM-RR'),2);

commit;