DROP TABLE "NEWS_AUTHOR";
DROP TABLE "NEWS_TAG";
DROP TABLE "AUTHOR";
DROP TABLE "TAG";
DROP TABLE "COMMENTS";
DROP TABLE "NEWS";

CREATE TABLE "NEWS" ("NEWS_ID" NUMBER(20,0), "TITLE" NVARCHAR2(100), "SHORT_TEXT" NVARCHAR2(100), 
"FULL_TEXT" NVARCHAR2(2000), "CREATION_DATE" TIMESTAMP, "MODIFICATION_DATE" DATE, "VERSION" NUMBER(20, 0) DEFAULT 1);
ALTER TABLE "NEWS" ADD CONSTRAINT "NEWS_PK" PRIMARY KEY ("NEWS_ID");
ALTER TABLE "NEWS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
ALTER TABLE "NEWS" MODIFY ("SHORT_TEXT" NOT NULL ENABLE);
ALTER TABLE "NEWS" MODIFY ("FULL_TEXT" NOT NULL ENABLE);
ALTER TABLE "NEWS" MODIFY ("TITLE" NOT NULL ENABLE);
ALTER TABLE "NEWS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
ALTER TABLE "NEWS" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
DROP SEQUENCE "NEWS__SEQ";
CREATE SEQUENCE  "NEWS__SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30;
  
CREATE TABLE "AUTHOR" ("AUTHOR_ID" NUMBER(20,0), "NAME" NVARCHAR2(30), "EXPIRED" TIMESTAMP (6),
"VERSION" NUMBER(20, 0) DEFAULT 1);
ALTER TABLE "AUTHOR" ADD CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("AUTHOR_ID");
ALTER TABLE "AUTHOR" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
ALTER TABLE "AUTHOR" MODIFY ("NAME" NOT NULL ENABLE);
DROP SEQUENCE "AUTHOR_SEQ";
CREATE SEQUENCE  "AUTHOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30;

CREATE TABLE "NEWS_AUTHOR" ("NEWS_ID" NUMBER(20,0), "AUTHOR_ID" NUMBER(20,0));
ALTER TABLE "NEWS_AUTHOR" MODIFY ("NEWS_ID" NOT NULL ENABLE);
ALTER TABLE "NEWS_AUTHOR" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
ALTER TABLE "NEWS_AUTHOR" ADD CONSTRAINT "NEWS_AUTHOR_FK1" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "NEWS_AUTHOR" ADD CONSTRAINT "NEWS_AUTHOR_FK2" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "AUTHOR" ("AUTHOR_ID") ON DELETE CASCADE ENABLE;
	  
CREATE TABLE "TAG" ("TAG_ID" NUMBER(20,0), "TAG_NAME" NVARCHAR2(30), "VERSION" NUMBER(20, 0) DEFAULT 1);
ALTER TABLE "TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("TAG_ID");
ALTER TABLE "TAG" MODIFY ("TAG_ID" NOT NULL ENABLE);
ALTER TABLE "TAG" MODIFY ("TAG_NAME" NOT NULL ENABLE);
DROP SEQUENCE "TAG_SEQ";
CREATE SEQUENCE  "TAG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30;

CREATE TABLE "NEWS_TAG" ("NEWS_ID" NUMBER(20,0), "TAG_ID" NUMBER(20,0));
ALTER TABLE "NEWS_TAG" MODIFY ("NEWS_ID" NOT NULL ENABLE);
ALTER TABLE "NEWS_TAG" MODIFY ("TAG_ID" NOT NULL ENABLE);
ALTER TABLE "NEWS_TAG" ADD CONSTRAINT "NEWS_TAG_FK1" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "NEWS_TAG" ADD CONSTRAINT "NEWS_TAG_FK2" FOREIGN KEY ("TAG_ID")
	  REFERENCES "TAG" ("TAG_ID") ON DELETE CASCADE ENABLE;
	  
CREATE TABLE "COMMENTS" (	"COMMENT_ID" NUMBER(20,0), "COMMENT_TEXT" NVARCHAR2(100), "CREATION_DATE" TIMESTAMP, 
 "NEWS_ID" NUMBER(20,0));
ALTER TABLE "COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENT_ID");
ALTER TABLE "COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
ALTER TABLE "COMMENTS" MODIFY ("COMMENT_TEXT" NOT NULL ENABLE);
ALTER TABLE "COMMENTS" ADD CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
DROP SEQUENCE "COMMENT_SEQ";
CREATE SEQUENCE  "COMMENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30;

commit;