package com.mamay.inspection.dao;

import com.mamay.inspection.dbhelper.ProxyConnection;
import com.mamay.inspection.entity.Entity;
import com.mamay.inspection.exception.DAOException;
import java.util.List;

/**
 * This class represents the top of hierarchy for DAO classes
 *
 * <p>Contains description the most common methods
 *
 * @since 12 november 2014
 */
public abstract class AbstractDAO<K, T extends Entity> {
  protected ProxyConnection connection;

  public AbstractDAO(ProxyConnection connection) {
    this.connection = connection;
  }

  public abstract List<T> findAll() throws DAOException;

  public abstract T findEntityById(K id) throws DAOException;

  public abstract void delete(K id) throws DAOException;

  /**
   * @param entity - to be inserted into database
   * @return - autogenerated primary key for inserted entity
   * @throws DAOException - if there are any problems with database
   */
  public abstract K create(T entity) throws DAOException;

  public abstract void update(T entity) throws DAOException;
}
